sonar.projectKey=seu-usuario-github_seu-repositorio
sonar.organization=seu-usuario-github
sonar.sources=src
sonar.tests=src,E2E
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts
sonar.exclusions=dist/**,node_modules/**,coverage/**,playwright-report/**,test-results/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
