sonar.projectKey=alexandre-s-goncalves_portfolio
sonar.organization=alexandre-s-goncalves
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=src,E2E
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=dist/**,node_modules/**,playwright-report/**,test-results/**,src/main.tsx,src/setup.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.cpd.exclusions=src/i18n/locales/**/*
