name: tests

on:
  push:
    branches-ignore:
      - main

jobs:
  code-quality-and-tests:
    name: Code Quality and Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Check Code Linting
        run: npm run lint

      - name: Check Code Formatting
        run: npm run format -- --check

      - name: Run Unit Tests
        run: npm run test
